### ISSUE TITLE
Add  /version Endpoint in QuARC

### ISSUE THREAD

**Issue by binni979** [NASA-IMPACT/QuARC#36]
We are creating this issue to solve this [issue](https://github.com/NASA-IMPACT/pyQuARC/issues/281).

We need to add  `/version` in the current QuARC API endpoint that returns the current versions of `pyQuARC` and `QuARC`. 
The endpoint should return a JSON response like:
{
    "pyquarc": "1.0.0",
    "quarc": "2.0.0"
}

**Comment by xhagrg** [comment]
#37
